// Generated by scripts/gen-relations.ts from prisma/schema.prisma. Do not edit.
export const RELATIONS: Record<string, Record<string, string>> = {
  User: {
    sessions: "Session",
    accounts: "Account",
    members: "Member",
    invitations: "Invitation",
  },
  Session: {
    user: "User",
  },
  Account: {
    user: "User",
  },
  Verification: {},
  Organization: {
    members: "Member",
    invitations: "Invitation",
    settings: "AgencySettings",
    properties: "Property",
    units: "Unit",
  },
  Member: {
    organization: "Organization",
    user: "User",
  },
  Invitation: {
    organization: "Organization",
    user: "User",
  },
  AgencySettings: {
    agency: "Organization",
  },
  AutomationQuota: {},
  Property: {
    agency: "Organization",
    units: "Unit",
  },
  Unit: {
    agency: "Organization",
    property: "Property",
    opportunities: "Opportunity",
    showings: "Showing",
    applications: "Application",
    holds: "UnitHold",
    leases: "Lease",
    residencies: "Residency",
    tickets: "MaintenanceTicket",
  },
  Lead: {
    opportunities: "Opportunity",
    showings: "Showing",
    applications: "Application",
    leases: "Lease",
    residencies: "Residency",
  },
  Opportunity: {
    lead: "Lead",
    unit: "Unit",
    interests: "IndicationOfInterest",
    stageEvents: "StageEvent",
  },
  StageEvent: {
    opportunity: "Opportunity",
  },
  IndicationOfInterest: {
    opportunity: "Opportunity",
  },
  AvailabilityRule: {},
  AvailabilityException: {},
  Showing: {
    unit: "Unit",
    lead: "Lead",
  },
  Application: {
    lead: "Lead",
    unit: "Unit",
    criteria: "ScreeningCriteria",
    residences: "ResidenceHistory",
    consents: "ConsentRecord",
    references: "ReferenceRequest",
    screeningRequests: "ScreeningRequest",
    steps: "AgentStep",
    recommendations: "Recommendation",
    decisions: "Decision",
    hold: "UnitHold",
    lease: "Lease",
    adverseAction: "AdverseActionNotice",
    tasks: "ApprovalTask",
    documents: "GeneratedDocument",
  },
  ResidenceHistory: {
    application: "Application",
    references: "ReferenceRequest",
  },
  ConsentRecord: {
    application: "Application",
  },
  ReferenceRequest: {
    application: "Application",
    residence: "ResidenceHistory",
    response: "ReferenceResponse",
  },
  ReferenceResponse: {
    request: "ReferenceRequest",
  },
  ScreeningCriteria: {
    applications: "Application",
  },
  ScreeningRequest: {
    application: "Application",
    result: "ScreeningResult",
  },
  WebhookEvent: {},
  ScreeningResult: {
    request: "ScreeningRequest",
  },
  AgentStep: {
    application: "Application",
  },
  LlmCall: {},
  Recommendation: {
    application: "Application",
  },
  Decision: {
    application: "Application",
  },
  ApprovalTask: {
    application: "Application",
  },
  AdverseActionNotice: {
    application: "Application",
  },
  OutboxMessage: {},
  GeneratedDocument: {
    application: "Application",
  },
  UnitHold: {
    unit: "Unit",
    application: "Application",
  },
  Lease: {
    application: "Application",
    unit: "Unit",
    signer: "Lead",
    signatures: "Signature",
    residency: "Residency",
  },
  Signature: {
    lease: "Lease",
  },
  Residency: {
    unit: "Unit",
    lease: "Lease",
    lead: "Lead",
    tickets: "MaintenanceTicket",
  },
  MaintenanceTicket: {
    unit: "Unit",
    residency: "Residency",
    photos: "TicketPhoto",
    comments: "TicketComment",
    events: "TicketEvent",
  },
  TicketPhoto: {
    ticket: "MaintenanceTicket",
  },
  TicketComment: {
    ticket: "MaintenanceTicket",
  },
  TicketEvent: {
    ticket: "MaintenanceTicket",
  },
  SlaPolicy: {},
  AuditLog: {},
  ProcessCheck: {},
};
