// Writes src/server/relations.generated.ts: for every model, which fields are relations and to
// which model. The tenant client uses it to spot nested writes and cross-tenant includes.
import { readFileSync, writeFileSync } from "node:fs";

export function relationMap(schema: string): Record<string, Record<string, string>> {
  const models = [...schema.matchAll(/^model (\w+) \{([\s\S]*?)^\}/gm)];
  const names = new Set(models.map((m) => m[1]));
  const out: Record<string, Record<string, string>> = {};
  for (const [, name, body] of models) {
    out[name] = {};
    for (const line of body.split("\n")) {
      const m = line.trim().match(/^(\w+)\s+(\w+)(\[\])?\??/);
      if (m && names.has(m[2])) out[name][m[1]] = m[2];
    }
  }
  return out;
}

export function render(map: Record<string, Record<string, string>>) {
  return `// Generated by scripts/gen-relations.ts from prisma/schema.prisma. Do not edit.\nexport const RELATIONS: Record<string, Record<string, string>> = ${JSON.stringify(map, null, 2)};\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync("src/server/relations.generated.ts", render(relationMap(readFileSync("prisma/schema.prisma", "utf8"))));
  console.log("wrote src/server/relations.generated.ts");
}
